### ISSUE TITLE
XYZ rather than TMS

### ISSUE THREAD

**Issue by tmcw** [nicoptere/light-map#1]
OSM, Stamen, MapQuest, and Mapbox are all XYZ tile providers, rather than TMS - the TMS standard specifies a flipped y coordinate that has gone out of style amongst all major map providers.

**Comment by nicoptere** [comment]
actually, I thought 'TMS' was a generic term and wasn't aware that it had a [specification](http://wiki.osgeo.org/wiki/Tile_Map_Service_Specification)... thanks for the heads up :) I believe the use of quadkeys to target unique tiles is a practicality worth encoding only the the positive space. 
![TMS tiles system](http://wiki.osgeo.org/images/e/e7/Tms.png) 
encoding quadkeys with negative IDs ( -1,-1 ) would make things more difficult even though it would be more intuitive as it would work like the lat/lon system.

do you think I should change the description? (TMS >XYZ)

**edit** this is the first issue I have to manage, I'm a bit lost ^^

**Comment by tmcw** [comment]
Yep! Probably call these XYZ instead of TMS - the difference is minimal, but when they're mixed up you'll end up with a bizarrely flipped map :)

**Comment by nicoptere** [comment]
ok, I'll change the readme & "doc" page and bear this in mind for the future :) 
actually the Map object flips the latitude in some cases to get the mercator to properly compute coordinates & render the tiles in the (Y-down) screen space. 
I'll close after pushing, thanks.

**Comment by nicoptere** [comment]
made the changes.
